### ISSUE TITLE
Segwit and non-segwit rawtransaction

### ISSUE THREAD

**Issue by ozosbittglobal** [elevenyellow/coinfy#12]
Hello, 

I tried doing a altcoin on your explorer, trying out your development. Every time I tried sending a transaction, I will get error due to rawtx send out as segwit. Apprently Insighttx doesn't support segwit.

16: bad-txns-vin-empty. Code:-26

Any Ideas how to send POST as legacy rawtransaction?

**Comment by Josema** [comment]
It depends on the node behind insight. If you are on BTC you can use Blockcypher as the provider to send your rawtx. We don't have backend at this moment so we depend on the free providers that implement it. Sorry about that.
