### ISSUE TITLE
i didnt get my bitcoin

### ISSUE THREAD

**Issue by plzdontcry** [elevenyellow/coinfy#14]
On blockchain its shows, like i got it: https://www.blockchain.com/btc/address/3EvmQquwdzCDednXjgMHj24eL6SRpapXSv
but i didnt!!!

**Comment by plzdontcry** [comment]
it doesnt show anything in my wallett

**Comment by Josema** [comment]
It should be working now.

**Comment by plzdontcry** [comment]
its good, thanks you are the best !:)

Josema Gonzalez <notifications@github.com> ezt írta (időpont: 2019. jún.
19., Sze, 14:55):
