### ISSUE TITLE
Not able to set GAS LIMIT to send Ethereum transaction

### ISSUE THREAD

**Issue by fsfIndravi** [elevenyellow/coinfy#15]
Hello,

how can I set GAS LIMIT for Ethereum send transaction in Coinfy wallet?

I can only set network fee, but not GAS LIMIT!

Regards,
Alex

**Comment by fsfIndravi** [comment]
Without enough required GASLIMIT (32000) I can't send Ether (transaction fails instantly!!!!)

**Comment by Josema** [comment]
The default Gas limit is 21000 at this moment. This is a recent tx: https://etherscan.io/tx/0x0531b5870e2aaa4b9da9e34fb4f50e2575d24a04f32beecc48d6d9cb30828584

And it has 21000 as Gas Limit. Are you sure is failing because of that?

**Comment by fsfIndravi** [comment]
Yes, 100%. After I tried 2 times to send the transaction and it failed, I used MyEtherWallet.com with the same address and private key - it allows to adjust GAS LIMIT. I set 32000 GAS LIMIT and the transaction went OK.

**Comment by fsfIndravi** [comment]
Here is the transaction:
https://etherscan.io/tx/0xe6381a9179476a1cee87a5c7b7af3e760b943830c3b716e99be5a8327e0d91b9

Gas Limit:
31,029
Gas Used by Transaction:
**30,103 (97.02%)**

So, as you see, for this particular transaction 21000 Gas Limit was not enough.

**Comment by Josema** [comment]
This one is very recent and uses 21000. Do you have the tx id of your failed txs?

**Comment by fsfIndravi** [comment]
According to etherscan.com:
Gas Used by Transaction:
30,103 (97.02%)

It's 30,103 Gas and not 21000 as you say. It's 30,103!

**Comment by fsfIndravi** [comment]
Here is failed tx:
https://etherscan.io/tx/0x250d006914334fdb5efed9af2b95aa5422f1d1088c834ce643daa25e3cf64bab

Gas Used by Transaction:
21,000 (100%)

Any more evidence 21,000 Gas was not enough ?

**Comment by Josema** [comment]
I changed the default gas to 31000 https://github.com/elevenyellow/coinfy/blob/master/src/api/coins/ETH.js#L66

We only have one field as Fee to be more homogenous with other assets. Bitcoin does not have the gas limit concept. So we wanted a solution that fits for all type of assets.

Sorry for the inconvenience.
