### ISSUE TITLE
Hot reload does not work.

### ISSUE THREAD

**Issue by Aurelyn10** [elevenyellow/coinfy#2]
I tried to compile this source in my macOs.
I typed `npm run dev ` and tried to change something and save, but not working with hot reloading mode.
The change is shown only after when `npm run build`.
How to work on this source in develop mode with hot reloading?

**Comment by Josema** [comment]
Sometimes does not work depending of the file you edit. But if you edit a React component it updates automatically.

**Comment by Aurelyn10** [comment]
Did you check?
Simply I tried to erase  <SideMenu /> component in App.js.

**Comment by Josema** [comment]
It works for me :/
