### ISSUE TITLE
Btc Not deposited wallet address.

### ISSUE THREAD

**Issue by Websoli** [elevenyellow/coinfy#38]
I have send some BTC to coinfy wallet and however its not deposited to my wallet, when i check in the blockchain the transaction was confirmed what is going here ?
and also when i try to transfer ETH from coinfy to different exchange its gives this error 
{"code":-32000,"message":"only replay-protected (EIP-155) transactions allowed over RPC"}.
Can some one please help?

**Comment by Josema** [comment]
Hi, at this moment we are not maintaining Coinfy. We recommend you exporting your 12 word mnemonic into https://app.monedero.com to have access to your funds. If you need help to make this process, please let me know.

**Comment by Websoli** [comment]
Hello can you please help me with this issue, i have followed the steps to export the wallet to monedero but i still dont see the funds in it.

**Comment by Josema** [comment]
Try importing your 12 words mnemonic into [tokenpocket](https://otemzi.medium.com/steps-to-import-mnemonic-phrase-words-to-tokenpocket-wallet-ea82080707a1).

**Comment by Websoli** [comment]
the 12 Mnewmonic was imported to the wallet you referred Monedero but there is no fund, so i check the BTC Private key on https://www.bitaddress.org/   and the private key comes up that it is link with the new BTC address of Monedero but it doesnt show the old BTC address of Coinfy, So i think the Coinfy BTC Address is not link with the 12 Mnewmonic of coinfy nor the private key is link with the BTC address of Coinfy.

**Comment by Websoli** [comment]
@Josema  I have attached a couple of files for your reference. Thank you
[Address_ 33GSH1fAwPNWZ5tYrCg78oLqMBAXA8efMA _ Blockchain Explorer.pdf](https://github.com/elevenyellow/coinfy/files/8134899/Address_.33GSH1fAwPNWZ5tYrCg78oLqMBAXA8efMA._.Blockchain.Explorer.pdf)
[Coinfy.pdf](https://github.com/elevenyellow/coinfy/files/8134904/Coinfy.pdf)

**Comment by Josema** [comment]
> 

The problem is that Coinfy is using the Segwit version to generate address. And Monedero.com is using Segwit bench32.
If you go to https://kimbatt.github.io/btc-address-generator/?page=address-details and you import this private key `L1bQsnaYNYizWfGpzfhHsYTfz1r34CesTihFdtJ4roX8ZCbVuFqQ` this is the result:

- Segwit: `3MBw8MbhdT3xqQP2YsvLEVy7bg4DTBPDtM` (Coinfy)
- Segwit (bech32): `bc1qcwwt7f2k34jh4zvf8snx0l47665dm24a9apthm` (Monedero)
- Legacy: `1JqJYMej3PJYkGW7dqcEArAKBnvQok6aCH` (Bitaddress.org)

I think is a lot of money so you must be careful. If I were you I would use Exodus. It will move your funds to your new Exodus account/privatekeys. Make sure that you save your new exodus mnemonic safely.
https://support.exodus.com/article/87-can-i-import-a-private-key

**Comment by Websoli** [comment]
So how i get access to the funds?

**Comment by Josema** [comment]
1. Export your Private key unencrypted (WIF) from Coinfy.
2. Import that private key in Exodus

**Comment by Websoli** [comment]
![download](https://user-images.githubusercontent.com/100252392/155597562-d9c37252-d7f8-4570-a2c3-833db4058b94.jpg)
this is the message i am getting on exodus

**Comment by Josema** [comment]
Remove this message, do not share private keys!

Can you send the address to check if it has funds?

**Comment by Websoli** [comment]
bc1q4nan35v30nvawvuw2hwm743jmwxyw460uht9q6

**Comment by Websoli** [comment]
this is the Address for Exodus

**Comment by Josema** [comment]
Import the private key in exodus. Make sure that you are in the Bitcoin tab. Otherwise will throw an error.
![image](https://user-images.githubusercontent.com/1819888/155599549-c227b9ac-050d-44cf-94bb-997001fcc5dd.png)

**Comment by Websoli** [comment]
HI @Josema thank you so much for your help i really appreciate it, i got the funds and got it resolved thank you once again you saved my life.

**Comment by Josema** [comment]
Just one more thing. You shared with me your private key. I would have be able to steal your BTC. So be very careful out there. Maybe next time the person that gets your key is not like me 😂

Have a good day. Cheers!

**Comment by Websoli** [comment]
ok bro thank you so much i know i should not have, and i will keep that in mind in the future. God bless you
