### ISSUE TITLE
Failed to execute 'btoa' on 'Window'

### ISSUE THREAD

**Issue by Gershon-A** [elevenyellow/coinfy#9]
Hello,
i face following error when try to download backup:
`Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
`
`data:btoa(JSON.stringify(t)),a:e,name:"YOU_MUST_RENAME_THIS_FOR_SECURITY"}
`
Because of that error , backup file download not working
\src\store\actions.js
```
    downloadFile({
        data: btoa(JSON.stringify(data)),
        a: a_element,
        name: 'YOU_MUST_RENAME_THIS_FOR_SECURITY'
    })
```
Seems , here need be some additional function to strip illegal characters.

**Comment by Josema** [comment]
Hi, can you provide the name of your assets to check if happen the same to me?

**Comment by Josema** [comment]
No one of those has Latin or weird characters

**Comment by Gershon-A** [comment]
Right. But some how , the characters is added to backup file.
I'm think , add function to strip illegal characters is good idea.
What You think ?

**Comment by Josema** [comment]
Fixed and deployed:
https://github.com/elevenyellow/coinfy/commit/a248ea370baaef0b9bdbe2b83c67ae1727246c93#diff-44d54346987880ad4492a03e86b662b7

Thank you :)
